[package]
name = "throwie-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inflate = "0.4.5"
num = "0.4.3"
num_enum = "0.7.3"
thiserror = "2.0.8"
tokio = { version = "1.45.1", features = ["full", "socket2"] }
prost = "0.13.5"
prost-types = "0.13.5"
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.23"
socket2 = { version = "0.5.10"}
num_cpus = "1.17.0"
dashmap = "7.0.0-rc2"
ringbuffer = "*"
tokio-postgres = {  version = "0.7.13", features = ["with-chrono-0_4", "with-eui48-1"] }
futures = "0.3.31"
chrono = "0.4.41"
eui48 = { version = "1.1.0"}

[build-dependencies]
protoc-rust = "3.0.0-alpha.2"
prost-build = "0.13.5"
