[package]
name = "throwie-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "*"
inflate = "0.4.5"
influxdb = { version = "0.7.2", features = ["derive"] }
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
num = "0.4.1"
num_enum = "*"
protobuf = "3.3.0"
thiserror = "*"
tokio = { version = "1.28.1", features = ["full"] }
config = "0.14.0"
serde = "*"
serde_derive = "1.0.163"

[build-dependencies]
protobuf = "3.3.0"
protobuf-codegen = "3.3.0"
protoc-rust = "^2.0"