[package]
name = "throwie-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
influxdb = { version = "0.6", features = ["derive"] }
log = "*"
protobuf = "3"
thiserror = "*"
tokio = { version = "1.28.1", features = ["full"] }
sysinfo = "0.29.0"
unix-ts = "0.4.1"

[build-dependencies]
protobuf-codegen = "3"
protoc-rust = "^2.0"