[build]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [                                  # additional commands to run prior to building the package
    "dpkg --add-architecture $CROSS_DEB_ARCH", 
    "apt-get update",
    "apt-get --assume-yes install libprotobuf-dev:$CROSS_DEB_ARCH protobuf-compiler:$CROSS_DEB_ARCH"
]   
passthrough = ["RUST_BACKTRACE=1"]
