[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt install -y protobuf-compiler",
]
[build.env]
passthrough = ["RUST_BACKTRACE=full"]
