[app]


[message]
address = "0.0.0.0"
buffer_size = 2000
port = 6969

[csi]
frame_size = 145

[influx]
protocol = "https"
address = "csi-hub"
port = 8086
#username = "influx"
write_batch_size = 1000
database = "influx"
csi_metrics_measurement = "csi_metrics"
sensor_telemetry_measurement = "telemetry"