name: Build and Publish Docker Image

on:
  release:
    types: [created]
  # Add manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Fetch the latest release from GitHub
      - name: Fetch latest GitHub release
        id: get_release
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/Gi-z/throwie-server-rust/releases/latest | jq -r .assets[0].browser_download_url)
          echo "Latest release download URL: $LATEST_RELEASE_URL"
          curl -L $LATEST_RELEASE_URL --output ./throwie-server

      # Step 2: Set up Docker Buildx (for building multi-platform images, optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v8
          push: true
          tags: |
            ghcr.io/gi-z/throwie-server-rust:latest
