name: Release
on:
  # schedule:
  # - cron: '0 0 * * *' # midnight UTC

  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    ## - release

jobs:
  release:
    name: Release - aarch64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0.0.15
        with:
          command: build
          target: aarch64-unknown-linux-gnu
          args: "--locked --release"
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          binary-name: throwie-server
          target: aarch64-unknown-linux-gnu
