name: Release
on:
  # schedule:
  # - cron: '0 0 * * *' # midnight UTC

  push:
    paths:
      - version.txt

jobs:
  release:
    name: Release - aarch64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Read file contents"
        uses: guibranco/github-file-reader-action-v2@latest
        id: get_version
        with:
          path: "version.txt"
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0.0.15
        with:
          command: build
          target: aarch64-unknown-linux-gnu
          args: "--locked --release"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "target/aarch64-unknown-linux-gnu/release/throwie-server"
          tag_name: ${ steps.get_version.outputs.contents }
