name: Release
on:
  # schedule:
  # - cron: '0 0 * * *' # midnight UTC

  push:
    paths:
      - version.txt

env:
  TARGET: aarch64-unknown-linux-musl

jobs:
  release:
    name: Release - aarch64
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Read version from version.txt
        id: get_version
        run: |
          VERSION=$(cat version.txt | tr -d '\n' | tr -d '\r')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Generate unique tag
        id: generate_tag
        run: |
          UNIQUE_TAG="${{ env.VERSION }}-build-${{ github.run_number }}"
          echo "Generated tag: $UNIQUE_TAG"
          echo "TAG_NAME=$UNIQUE_TAG" >> $GITHUB_ENV
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0.0.15
        with:
          command: build
          target: ${{ env.TARGET }}
          args: "--locked --release"
      - uses: qoomon/actions--create-tag@v1
        with:
          name: ${{ env.TAG_NAME }}
      - run: git push origin "${TAG_NAME}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ env.TARGET }}/release/throwie-server
            src/config/app.toml
          tag_name: ${{ env.TAG_NAME }}
          token: ${{ secrets.GH_TOKEN }}
